### ISSUE TITLE
ChatBot Design and Implementation

### ISSUE THREAD

**Issue by SudhaAmarnath** [SudhaAmarnath/CMPE295SpartansMastersProject#17]
Integrate Chatbot APIs to the app

**Comment by mukeshsahay** [comment]
Implemented the chatbot for GrabOn.

- View Profile
- Update Profile

  - Address
  - Phone Number
- View Posted Items
- Update an Item
  - Name
  - Description
  - Price
  - Status
- GrabOn Search (Search based on category)
